---
- name: Check if steam is installed
  command: dpkg-query -W steam
  register: steam_check_deb
  failed_when: steam_check_deb.rc > 1
  changed_when: steam_check_deb.rc == 1
- name: Download steam
  get_url: 
    url="{{ steam_url }}"
    dest="/tmp/{{ steam_package_name }}"
  when: steam_check_deb.rc == 1 
- name: Install my_package
  apt: deb="/tmp/{{ steam_package_name }}"
  sudo: true
  when: steam_check_deb.rc == 1
